name: Build, Test, and Deploy to Heroku

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.2.0'

      - name: Install dependencies
        run: npm install

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.2.0'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        env:
          CI: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.2.0'

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: da2799ac-e7da-46a2-956b-e081f7dd23f8
          heroku_app_name: zaunmap
          heroku_email: zhangwen.hu@stonybrook.edu